### PR TITLE
Support for hvyor talk comments

### PR DESCRIPTION
**Pull request by Ayush1325**
[Hvyor Talk](https://talk.hyvor.com/) is a privacy-focused, fully-featured commenting platform for blogs and news sites. I am using it on my personal blog, so I thought to open a PR if other people might be interested in using it.

### CODE REVIEW

**Comment by Jieiku** [comment]
Looks good, thank you!

**Comment by Jieiku** [comment]
I tested it a bit, their styles require unsafe-inline in the CSP, I opened a report about it: https://community.talk.hyvor.com/submissions/64dec56e8b15fc2614ac224b

Additionally, when I enabled Hyvor for abridge I was getting a bit of (Flash of inAccurate coloR Theme)[https://css-tricks.com/flash-of-inaccurate-color-theme-fart/]

I tried changing the scripts from async to defer, but it did not help. The flash of inaccurate color may have been caused by the shadow dom that hyvor uses for styling, but i am honestly not sure, but once I disabled hyvor by default the flash of inaccurate color was gone.

The easiest way to reproduce this issue is by clicking into articles then using the browser back button. My default is a dark theme, and when I would hit the back button I was often getting a very small flash of white background, its very fast, and some people may not even notice, but it was there. Additionally it seemed to only be an issue in Firefox, Chrome did not display the issue...

For now I disabled hyvor in the demo because I want it working perfectly in both firefox and chrome.

**Comment by Ayush1325** [comment]
Sure. I personally use Firefox as well. 

I am using hyvor because I do not want to use Disqus, and commento has not been updated since 2021 (at least the GitHub version). I also do not want to host comments myself since I am not a devops or backend person. 

I did not notice those issues because, well, comments are pretty much an afterthought right now and only experimental on my blog. I might end up removing them if they don't serve much purpose.

Anyway, thanks for all your work. I love this theme.

**Comment by jalemann** [comment]
@Ayush1325 If you are looking for an alternative maybe check out Cactus Comments which is matrix based and can work even if you don’t host your own matrix homeserver.

https://cactus.chat/

**Pull request merged**
