### PR TITLE
Allow custom styles

### PR DESCRIPTION
**Pull request by simbleau**
Allow custom styles without the need to modify the theme - Simply implement your own custom.scss in your zola directory.

### CODE REVIEW

**Comment by simbleau** [comment]
This might've been the wrong way to go about it... My intention is to use the light theme always, without having to modify your theme in any way. I thought by writing my own custom.scss file in my zola root, it would overwrite the custom.scss I planted here. Not sure what the right path is.

**Comment by Jieiku** [comment]
I think the easier way might be to generate all 3 css styles (auto, light, dark)

Then have an option in the config.toml that specifies which theme file to load (auto, light, dark)

I will add this option.

**Comment by Jieiku** [comment]
I will work on this one now.

**Comment by Jieiku** [comment]
I will work on this one now.

**Comment by Jieiku** [comment]
This is now finished, style can be configured in the config.toml file

**Pull request closed without merging**
