### PR TITLE
point extra_syntaxes_and_themes at the correct directory

### PR DESCRIPTION
**Pull request by pentop**

### CODE REVIEW

**Comment by pentop** [comment]
when following the instructions. extra_syntaxes_and_themes needs editing before the site will start

**Comment by simbleau** [comment]
Is this not bugged? getzola/zola#1865

**Comment by Jieiku** [comment]
I will point it at both and make a note in the config.toml about what I believe is a bug.

**Comment by Jieiku** [comment]
woops, should have had my coffee first

**Comment by Jieiku** [comment]
@simbleau does this actually work for you?

**Comment by simbleau** [comment]
@ Work - will test later. :)

**Comment by Jieiku** [comment]
no problem, thanks.

**Comment by pentop** [comment]
> @simbleau or @pentop does this actually work for you?
> 
> I had to actually copy the themes into my root sites "highlight_themes" directory, specify the theme subpath did not work for me.
> 
> If this is indeed working for you, may I ask what version of Zola your running?

Works for me as far as I can tell (I'm a zola newb). I'm on zola 0.15.3

**Comment by simbleau** [comment]
Thought I commented already - it works. :)

**Comment by Jieiku** [comment]
Thanks! I closed the bug report at zola, I also updated the readme and the config.toml

**Pull request merged**
