### PR TITLE
Fixed icon viewboxes

### LINKED ISSUE #36: Issues with Icons
The icons I uploaded occupy their viewbox perfectly, maintaining aspect ratio. However I just realized that the "feather icons" and websites you got from have margins embedded into the SVG. Not sure by how much, but is noticeable. My icons look a tad big in comparison.

### PR DESCRIPTION
**Pull request by simbleau**
Closes #36. There will be a merge conflict with #37 when the time comes. Keep changes from #37 but keep the viewbox of '-1.1 -1.1 26.2 26.2'.

### CODE REVIEW

**Comment by Jieiku** [comment]
I prefer to keep the viewbox 0 0 24 24 on all icons, but I can see what your trying to accomplish, get them looking horizontally equivalent. I will do some work on this after lunch, a couple of my icons need a little attention as well.

**Comment by simbleau** [comment]
> I prefer to keep the viewbox 0 0 24 24 on all icons, but I can see what your trying to accomplish, get them looking horizontally equivalent. I will do some work on this after lunch, a couple of my icons need a little attention as well.

Awesome!

I am guessing you used the feather icons because they are probably smaller file size, however, if you wanted to some nicer looking icons: https://simpleicons.org and they come as decals which can be easily styled.

**Comment by simbleau** [comment]
Fixed the merge conflict.

**Comment by Jieiku** [comment]
I am in Washington state, its a late lunch

**Comment by simbleau** [comment]
> I am in Washington state, its a late lunch, and yes I always use minimal resources when possible. The feather icons look really good in my opinion but I will checkout the ones you linked.

I didn't even try this at first, but they also have BuyMeACoffee, ResearchGate, and GitHub Sponsors. Go figure. I had to rip those from branding websites myself... :/

**Comment by Jieiku** [comment]
I adjusted those icons and a couple others, we can track this here, looks good to me now, but we can track this here https://github.com/Jieiku/abridge/issues/36 if you find anything else.

**Pull request closed without merging**
