### PR TITLE
Add pagefind search to abridge

### PR DESCRIPTION
**Pull request by Hysterelius**
I have added a new `pagefind.index.js`, which can successfully build the index.

What needs to be fixed:

- [x] Multilingual support
- [x] Minify js files
- [x] Properly edit `package_abridge.js`
- [x] Put index files in proper location
- [x] Actually use search results in search
- [x] Remove `console.log`s for testing

### CODE REVIEW

**Comment by Hysterelius** [comment]
@Jieiku The pagefind has to write to static to make sure that all the files get included in `public/`, do you want all these files to be added to git?

```bash
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package_abridge.js
	modified:   static/js/abridge.min.js
	modified:   static/js/abridge_nopwa.min.js
	modified:   static/js/pagefind.index.js
	modified:   static/sw.js
	modified:   static/sw.min.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	pagefind-entry.json
	pagefind-highlight.js
	pagefind-modular-ui.css
	pagefind-modular-ui.js
	pagefind-ui.css
	pagefind-ui.js
	pagefind.en_1ddc24c138.pf_meta
	pagefind.js
	static/js/fragment/
	static/js/index/
	static/js/pagefind-entry.json
	static/js/pagefind-highlight.js
	static/js/pagefind-modular-ui.css
	static/js/pagefind-modular-ui.js
	static/js/pagefind-ui.css
	static/js/pagefind-ui.js
	static/js/pagefind.en_f0696ce0be.pf_meta
	static/js/pagefind.js
	static/js/wasm.en.pagefind
	static/js/wasm.unknown.pagefind
	wasm.en.pagefind
	wasm.unknown.pagefind
```

**Comment by Jieiku** [comment]
Initially it is fine to add whatever you need to add to static, it can always be changed later if needed.

I have been busy with work and will be a couple more days but I can't wait to check this out once I get a little down time.

**Comment by Hysterelius** [comment]
I just wondering how you do testing with abridge?
Like the `base url` attribute means that it tries to fetch from netlify and when I tried to change it to `localhost` I got some weird errors...
image

**Comment by Jieiku** [comment]
For most things I test using `zola serve`.

When I want to test a live build I push it to one of my development containers in my proxmox server. I have haproxy handing SSL termination and just hardcode a host override in the unbound dns resolver (but you could just as easily do it in your hosts file.)

I use the following bash script to build a site and push it to my container:

```bash
    cd ~/.dev/mytestdomain.com
    rsync themes/abridge/package_abridge.js package_abridge.js
    rsync themes/abridge/package.json package.json
    git submodule update --init --recursive
    git submodule update --remote --merge
    npm run abridge
    cd public
    # The following line is optional it is just to pre gzip/brotli the content to save some cpu cycles when serving content.
    find ~/.dev/mytestdomain.com/public -type f -regextype posix-extended -regex '.*\.(htm|html|css|js|json|xml|xsl|txt|svg|otf|eot|ttf|webmanifest)' -exec gzip --best -k -f {} \+ -exec brotli --best -f {} \;
    # rsync transfers the data to the development container
    rsync -zvrhog --chown=www-data:www-data --delete ~/.dev/mytestdomain.com/public/ webdev:/var/www/mytestdomain.com
```

**Comment by Hysterelius** [comment]
I was able to add `pagefind` to `abridge` :)
image

It probably needs a look over and a bit more testing.

I did put all the `pagefind` files in the `.gitignore`, as on every build they would regenerate leading to a large amount of `pagefind` files in `static` directory, so it is probably good to delete all those files when the `package_abridge.js` script runs.

**Comment by Jieiku** [comment]
Awesome, thanks for your work on this! I tried it out a moment ago and got the following error:

```
git clone https://github.com/Hysterelius/abridge
cd abridge
npm run abridge
```

```
> abridge-bundle@2.0.0 abridge
> node -e "if ( require('fs').existsSync('./themes/abridge/package_abridge.js')) {require('fs').copyFileSync('./themes/abridge/package_abridge.js', './package_abridge.js')}" && node package_abridge.js

Zola Build to generate files for minification:
Creating index...
node:fs:1525
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/home/jieiku/.dev/abridge-pagefind/abridge/public'
    at Object.readdirSync (node:fs:1525:3)
    at createIndex (/home/jieiku/.dev/abridge-pagefind/abridge/static/js/pagefind.index.js:13:22) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/jieiku/.dev/abridge-pagefind/abridge/public'
}

Node.js v18.20.3
```

It appears the error happens when zola build is not ran first, so there is no `public` directory. I would like to resolve that issue. I am still very busy (13 hour days), but should have some free time by Monday I hope.

I did issue a manual zola build so that I could go ahead and test it out, and it seems to work excellent, and the site integration looks great too!

**Comment by Hysterelius** [comment]
Yeah, I was having a bit of problem running my pagefind search code. 

I originally placed it so it was running like this:

```bash
@ first Zola build

* Build pagefind index
* Edit pagefind index

@ minify files
@ bundle files
@ second Zola build (for hashes)
```

Put due to its async code it led to it running like this:
```bash
@ first Zola build

* Build pagefind index

@ minify files
@ bundle files
* Edit pagefind index
@ second Zola build (for hashes)
```

Which meant that the improper `js` code was being placed in the bundle, which led to errors in the code and I couldn't figure out how to force it to run all the async code at once (I know that is not what async is meant for, but pagefind requires async).

So, I had to put the pagefind script at the start.

```bash
* Build pagefind index
* Edit pagefind index

@ first Zola build

@ minify files
@ bundle files
@ second Zola build (for hashes)
```

Which led to the error you saw, I was just writing this to see if you know anything that could fix this issue.


I am also going to edit the pagefind files so they can properly adding into the git tracking - so that you can actually deploy the site properly.

---
Todo:
- [ ] Edit pagefind hashes
- [ ] Put `config.toml` back to normal
- [ ] Double check the `pagefind.search.js` file

**Comment by Hysterelius** [comment]
I have fixed all the issues and have done some testing :)

The pagefind files are still in the `.gitignore` to stop the git directory ballooning and they are built everytime anyway. I also added a function to remove all the old indexes to make sure that the number of files don't get out of hand.

I have created a little `npm` script to automatically swap from on search library to another:
```bash
npm run search:elasticlunr

npm run search:pagefind
```
(This script is currently in the `static/js` folder, as I didn't know where else to put it)

**Comment by Jieiku** [comment]
All my testing shows no issues, looks good!

Your branch is missing a few of my latest commits, but it looks like the only affected file is config.toml, your pull request does not modify any of the other files I worked on.

**Comment by Hysterelius** [comment]
I just remarked it as draft before, as I realised I hadn't tested `pagefind` with a single language, which worked great. 
Everything should be good now!

**Pull request merged**
