### PR TITLE
Added theme logo

### PR DESCRIPTION
**Pull request by simbleau**
I created a quick logo in Inkscape, because every certified cool project needs a logo.

### CODE REVIEW

**Comment by Jieiku** [comment]
I didn't miss this. I am going to apply it to my dev site and use it for a bit, and brainstorm if there are any small tweaks I want to make before committing. Logos are something I usually put a lot of thought into. I like a lot of the design aspects you have used for it!

**Comment by simbleau** [comment]
All good. Be aware of Inkscape's metadata. I purposefully included Metadata in the SVG which gives licensing, authoring, etc, but Inkscape also saves your local path of the file by default, I found. You'll want to scrub the SVG for things that might dox you. For example, there was a variable which lead to '/home/simbleau/...' - where imbleau is my last name - and that might be privacy you value.

**Comment by Jieiku** [comment]
I got an idea for similar but different logo to this one. to use in the top left corner of the demo site.

What I am thinking is that I will make a small tweak to this one to match the one that I have in mind, and this one can be used at the top of the readme, and the one that I have in mind can be used in the top left of the demo site.

I need to make some small tweaks to this one so that the two will look similar

**Comment by simbleau** [comment]
Sounds good! You've got total creative freedom, this is your project. :)

**Comment by Jieiku** [comment]
Ok, here is the one I made for the top left corner of the demo site:

logo

**Comment by Jieiku** [comment]
Ok, here is the one I made for the top left corner of the demo site:

logo

Or one the scales to full width of its bounding box:

logo-full

**Comment by Jieiku** [comment]
The logo that you made does not display correctly in my file browser (dolphin), I tried to figure it out, im sure inkscape is to blame but I am not sure what is causing it:

**Comment by Jieiku** [comment]
Now Im thinking I should split these 2 paths into 3, and make the A frame a bit thicker than the bridge part, after looking at your logo and some font As

**Comment by simbleau** [comment]
Very cute! I like it more!

**Comment by Jieiku** [comment]
Here is the small tweak I applied to it, I thickened the outer A frame and thinned the bridge slightly:

logo min

full:

logo min-full

**Comment by Jieiku** [comment]
not really sure, still starring at it and thinking about it, let me know if you have any thoughts.

**Comment by Jieiku** [comment]
Your Logo gave me the inspiration and motivation to do this, thanks!

I incorporated some of the idea into the one I created.

**Pull request closed without merging**
