### PR TITLE
Added BuyMeACoffee Icon

### PR DESCRIPTION
**Pull request by simbleau**
This one is controversial to me... I'd like this merged in, but it slightly goes against the branding for Buy Me A Coffee. Currently, you have this setup generally such that logos are expected to be monotone, and this platform is probably the one example I can think of without a monotone logo. Maybe this needs some tweaks.

### CODE REVIEW

**Comment by Jieiku** [comment]
well you can see that most of the footer icons are colorized: https://jieiku.github.io/abridge-demo/

What I generally do is pick the dominant color used and use that, so we could use either yellow or monotone for the line/fill and it would look familiar to people.

The SVG icons you submitted seem large, im wondering if have ran them through svgomg yet: https://jakearchibald.github.io/svgomg/

Other than that I like all the extra icons! I appreciate it! Will hold off on merging incase you want to go ahead and minify them.

**Comment by Jieiku** [comment]
well you can see that most of the footer icons are colorized: https://jieiku.github.io/abridge-demo/

What I generally do is pick the dominant color used and use that, so we could use either yellow or monotone for the line/fill and it would look familiar to people.

The SVG icons you submitted seem large, im wondering if have ran them through svgomg yet: https://jakearchibald.github.io/svgomg/

Other than that I like all the extra icons! I appreciate it! Will hold off on merging incase you want to go ahead and minify them.

**Comment by simbleau** [comment]
The icons perfectly fit their bounding boxes, I made sure of that in Inkscape.




I also changed the color to yellow. I'm not a huge fan of how it looks - the real icon uses 2 colors as I mentioned.

**Comment by simbleau** [comment]
The reason the icons are large is because the icons you got from feathericon are a simple path, which can then be stroked to give it appearance.

The size of the SVG in the file is a symptom of the fact these logos I've added are shapes, not paths. We are not taking a single path curve and post-processing it with stroke. It is a closed shape with a lot of geometry.

s

**Comment by Jieiku** [comment]
If you rebase this I will merge it, thanks.

**Comment by Jieiku** [comment]
I have minified all 3 of the icons. I was aware that they were geometric shapes and not just a path. It had been a while since I minified the other icons. I thought that omgsvg took care of more of it than I remembered.

To really minify complex svg icons the trick is to open them in inkscape, select the node edit tool and select the object, then goto the Path menu and select simplify. You will notice that doing this really messed up the geometry, its not a one click and your done, but that tool really does get you close, then you just have to adjust and fix the curves.

Then finally with take the svg you saved from inkscape and minify it again in svgomg, this is the result of that same svg icon:



you can see the difference in these commits:

github-sponsor: https://github.com/Jieiku/abridge/commit/2186a5afd9d7409bac76ed67f211e976caebedde

researchgate: https://github.com/Jieiku/abridge/commit/7c6064fe4a86f404802452c0e056c0c9ef1f4d65

buymeacoffee: https://github.com/Jieiku/abridge/commit/364827d4c25c0da990e23d06138e9cb44c5034b0

**Pull request merged**
