### PR TITLE
 fix(img): fix the root path handling

### PR DESCRIPTION
**Pull request by 0x61nas**
fix the path handling, when path starts with `/` passed to the `img` shortcode

### CODE REVIEW

**Comment by Jieiku** [comment]
The root path was meant to give you a way to load resources from the base url, regardless of what subfolder your content may be in.

so for instance you have some content in a folder.

content/overview-images/  (https://abridge.netlify.app/overview-images/)

but you want to link to some random folder off the root domain eg images (https://abridge.netlify.app/images/)

you would be able to by using / at the start of the path withe the img shortcode.

as you can see all images load properly in the demo https://abridge.netlify.app/overview-images/

I am going to test these changes and see if they still do what I intended, or what problem you ran into.

eating dinner at the moment but will check it out shortly.

**Comment by 0x61nas** [comment]
when I want to use an image that n the `static` directory, is supposed to be under the root so we have to use `/` in the `src` attribute. 

```rs
{{img(src="/reactions/hold-cup-of-tea.gif" alt="Hold cup of tea")}}
```

this suppose to be translated into `http://127.0.0.1:1111/reactions/hold-cup-of-tea.gif` 'cuse we use `/, but the current implementation translates it to ` /page-path/http://127.0.0.1:1111/reactions/hold-cup-of-tea.gif` instead

**Comment by Jieiku** [comment]
ah that is helpful, so I can test this locally by trying to load an image from static.

I just need to make sure it does not break anything else, thanks for the info, one sec.

**Comment by 0x61nas** [comment]
I test it on the `overview-images` page and nothing breaks

**Comment by Jieiku** [comment]
on what page does it break?

**Comment by 0x61nas** [comment]
> 

` content/why-i-love-coding/index.md`

+ the error massage:
```
zola serve --open
Building site...
Error: Failed to serve the site
Error: Failed to render content of /mnt/work/me/weebsite/content/why-i-love-coding/index.md
Error: Reason: Failed to render img shortcode
Error: Reason: Failed to render 'shortcodes/img.html'
Error: Reason: Function call 'get_image_metadata' failed
Error: Reason: `get_image_metadata`: Cannot find path: /why-i-love-coding/http://127.0.0.1:1111/reactions/hold-cup-of-tea.gif

```

**Comment by Jieiku** [comment]
I am having trouble getting this to fail with the original code. on the overview-images I added two more root path entries and did a zola serve:


{{ img(src="/banner.png" alt="Ferris the Rustacean" w=600 h=400) }}
{{ img(src="/reactions/banner.png" alt="Ferris the Rustacean" w=600 h=400) }}



the site zola serve just fine.

Do you happen to have a simple test repo that I could do a git clone on and try zola serve it on my end, so that I can reproduce the problem?

**Comment by Jieiku** [comment]
oh I think im starting to see what you did.

**Comment by 0x61nas** [comment]
Aha, this's because you set the `w` and `h` attributes, the problem was from this block

https://github.com/Jieiku/abridge/blob/master/templates/shortcodes/img.html#L19-L24

**Comment by Jieiku** [comment]
yes, that's what allows you to omit the width and height, I can use zola/tera to check that meta data if omitted, and set it automatically..

**Comment by 0x61nas** [comment]
yep, but am too lazy to do this manually + I don't use avif files anyway

**Comment by Jieiku** [comment]
well I definitely reproduced the problem, simply by removing the explicitly set w and h on the overview-images page from all the examples, testing your fix now.

**Comment by Jieiku** [comment]
other images on the page now fail with this pull request:



I will see if I can work out the problem.

**Comment by Jieiku** [comment]
found one of the problems just now, metafile needed to be piped to safe:

**Comment by Jieiku** [comment]
I have this 100% fixed now, in all use cases for img, I am going to double check the imgswap shortcode too, new commit shortly. I really appreciate you pointing this out and helping me track down the cause, Thank You!

**Comment by Jieiku** [comment]
Should be fixed now: https://github.com/Jieiku/abridge/commit/f7c5bdd82cbad12b71dc9f5cd2b52536e5622ce8

Please let me know how it looks for you, Thanks Again!

**Comment by 0x61nas** [comment]
it works now, thx!

**Pull request closed without merging**
