### PR TITLE
Added GitHub Sponsor Icon

### PR DESCRIPTION
**Pull request by simbleau**
Adds a GitHub sponsor icon, if applicable.

### CODE REVIEW

**Comment by Jieiku** [comment]
did you run the icon through [svgomg](https://jakearchibald.github.io/svgomg/)

**Comment by simbleau** [comment]
Yes, it was adjusted in inkscape to make the viewbox match (24x24) then I minified it through there.

**Comment by simbleau** [comment]
The reason the file is large is not because it isn't minified - the reasoning is given here: https://github.com/Jieiku/abridge/pull/31#issuecomment-1122182529

**Comment by Jieiku** [comment]
Am I correct in assuming the deviation from the github pink color was because of contrast?

**Comment by simbleau** [comment]
I think the pink I chose is the official one, I color sampled it. But I am on GitHub light theme, so maybe GitHub has different colors lol.

**Pull request merged**
